### ISSUE TITLE
kelvin.xml git clone needs to have the https link

### ISSUE THREAD

**Issue by octavsly** [Kelvin-Ng/Kelvin-Gentoo-Overlay#1]
The git: link from the kelvin.xml contains a git: URL (git@github.com:Kelvin-Ng/Kelvin-Gentoo-Overlay.git) which can only be accessed with a key. 

It would be better to have the https://github.com/Kelvin-Ng/Kelvin-Gentoo-Overlay.git URL instead.

**Comment by Kelvin-Ng** [comment]
Thanks for reminding me. Fixed at 15f204d.
